<?php
$WPQP_var_array = array(
		WPQP.'_PLUGINDIR' =>  dirname(dirname(plugin_dir_path(__FILE__))),
		WPQP.'_PLUGIN_PAGES' =>  dirname(dirname(plugin_dir_path(__FILE__))).'/pages',
		WPQP.'_PLUGIN_TEMPLATES' =>  dirname(dirname(plugin_dir_path(__FILE__))).'/pages/templates',
		WPQP.'_PLUGINDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))),
		WPQP.'_PLUGIN_PGDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages',
		WPQP.'_PLUGIN_TMDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/templates',
		WPQP.'_PLUGIN_IMGDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/images',
		WPQP.'_PLUGIN_CSSDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/css',
		WPQP.'_PLUGIN_JSDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/js',
		WPQP.'_PLUGIN_SPLASHTEMDIR_PATH' =>  dirname(dirname(plugin_dir_path(__FILE__))).'/pages/inc/splashTemplates',
		WPQP.'_PLUGIN_SPLASHTEMDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/inc/splashTemplates',
		WPQP.'_PLUGIN_VIDSKINSDIR_PATH' =>  dirname(dirname(plugin_dir_path(__FILE__))).'/pages/inc/skins',
		WPQP.'_PLUGIN_VIDSKINSDIR_URL' => plugin_dir_url(dirname(dirname(__FILE__))).'pages/inc/skins',
		WPQP.'_INC_DIR' => dirname(plugin_dir_path(__FILE__)),
		WPQP.'_CLS_DIR' => dirname(plugin_dir_path(__FILE__)).'/classes'
);

$plugin_main_page =  array('_key'=>'_quoteRequests','Title'=>'Recieved Quote Requests','MenuText'=>'Quote Requests','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery','common-data','plugin_utilities','bootstrap-switch-master'),'cls'=>'page-main');

$plugin_menu_items = array(		
		'_mngSysSettings' => array('_key'=>'_mngSysSettings','Title'=>'System Settings','MenuText'=>'System Settings','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery','common-data','plugin_utilities')),
		'_basePricingOptions' => array('_key'=>'_basePricingOptions','Title'=>'Pricing Settings','MenuText'=>'Pricing Settings','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery','common-data','plugin_utilities')),
		'_serviceAvailability' => array('_key'=>'_serviceAvailability','Title'=>'Service Availability','MenuText'=>'Service Availability','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery','plugin_utilities','bootstrap-datepicker')),
		'_frontQuotePageView' => array('_key'=>'_frontQuotePageView','Title'=>'Quote Page View (Example)','MenuText'=>'Quote Page View','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery','common-data','plugin_utilities','jquery-steps-master')),
		'_licenseSettings' => array('_key'=>'_licenseSettings','Title'=>'License Settings','MenuText'=>'License','capability'=> 'manage_options','callback' => '_option_page_sub','page-style'=>true,'page-script'=>true ,'scriptDep' => array('jquery')),
);


$db_tables = array(
		"_hometypes" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`hometype` varchar(50) NOT NULL,
					`iconImageUrl` varchar(255) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_frequencies" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`frequency` varchar(50) NOT NULL,
					`iconImageUrl` varchar(255) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`isRecurring` int(11) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_startPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`hometype` varchar(50) NOT NULL,
					`frequency` varchar(50) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_bedroomPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`brcount` int(11) NOT NULL DEFAULT '0',					
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_bathroomPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`bathrcount` int(11) NOT NULL DEFAULT '0',
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_frqPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_petPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_sqfootagePricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`hometype` varchar(50) NOT NULL,
					`frequency` varchar(50) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`),PRIMARY KEY (`frequency`,`description`));"
				,
		"_servareaPricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`zipcode` varchar(50) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_availabledates" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`availabledate` date NOT NULL DEFAULT '1900-01-01',
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_surchargerates" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`dayofweek` varchar(200) NOT NULL DEFAULT 'Monday',
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `dayofweek` (`dayofweek`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_additionalserv" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`frequency` varchar(50) NOT NULL,
					`iconImageUrl` varchar(255) NOT NULL,
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,
		"_marketingref" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`price` numeric(10,2) NOT NULL DEFAULT '0',
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`),KEY `sortOrder` (`sortOrder`)) ;"
				,		
		"_syssettingss" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`hourlyrate` numeric(10,2) NOT NULL DEFAULT '0',
					`maxsqft` numeric(10,2) NOT NULL DEFAULT '0',
					`enablehourlyrate` int(11) NOT NULL DEFAULT '0',
					`stripeapistatus` int(11) NOT NULL DEFAULT '0',
					`apistripekey` varchar(100) NOT NULL DEFAULT ' ',
					`apistripevalue` varchar(100) NOT NULL DEFAULT ' ',
					`apistripetestkey` varchar(100) NOT NULL DEFAULT ' ',
					`apistripetestvalue` varchar(100) NOT NULL DEFAULT ' ',					
					`stripeapitype` int(11) NOT NULL DEFAULT '0',
					`stripeapicharge` int(11) NOT NULL DEFAULT '0',
					`greenropeapistatus` int(11) NOT NULL DEFAULT '0',
					`apigreenropekey`  varchar(100) NOT NULL DEFAULT ' ',	
					`apigreenropevalue`  varchar(100) NOT NULL DEFAULT ' ',
					`apigreenropeug` varchar(50) NULL,				
					`paypalstatus` int(11) NOT NULL DEFAULT '0',
					`apipaypalkey` varchar(20) NOT NULL DEFAULT ' ',
					`paypalsbstatus` int(11) NOT NULL DEFAULT '0',
					`fromemail` varchar(50) NOT NULL DEFAULT ' ',
					`confirmemail`  varchar(50) NOT NULL DEFAULT ' ',
					`supportemail` varchar(50) NOT NULL DEFAULT ' ',
					`supportphone`  varchar(20) NOT NULL DEFAULT ' ',
					`enablesysemail` int(11) NOT NULL DEFAULT '1',
					`custompmtmsg` text NULL,
					`infusionsoftstatus` int(11) NOT NULL DEFAULT '0',
					`infusionsoftclid` varchar(100) NOT NULL DEFAULT ' ',
					`infusionsoftclsec` varchar(100) NOT NULL DEFAULT ' ',
					`quotedisplayedtstagid` longtext NULL,
					`appointmentbookedtagid` varchar(100) NOT NULL DEFAULT ' ',
					`whowearemsg`  text NULL,
					`termandcondmsg` text NULL,
					`thankyounotemsg` text NULL,
					`msgSecondEmail` text NULL,
					`dateautoupdate` int(10) NULL,
					`customstyle` text NULL,
					`isDefOptIn` int(11) NOT NULL DEFAULT '1',
					`FTCExplanation`  text NULL,
					`gasettings` longtext NULL,
					`mqisfields` longtext NULL,
					`instexttab3`  text NULL,
					`instexttab4`  text NULL,
					`instexttab5`  text NULL,
					`instexttab6`  text NULL,
					`sortOrder` int(11) NOT NULL DEFAULT '0',	
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`)) ;" 
				,
		"_quotes" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`description` varchar(200) NOT NULL DEFAULT ' ',
					`startpricing` longtext NULL,
					`schedule` longtext NULL,
					`frequency` longtext NULL,
					`servicearea` longtext NULL,
					`sqfootage` longtext NULL,
					`bedrooms` longtext NULL,
					`bathrooms` longtext NULL,
					`pets` longtext NULL,
					`addServices` longtext NULL,
					`contactinfo` longtext NULL,
					`marketingRef` longtext NULL,
					`payment` longtext NULL,
					`totalprice` numeric(10,2) NOT NULL DEFAULT '0',
					`isHourlyRate` int(11) NOT NULL DEFAULT '0',
					`hourlyrate` longtext NULL,
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',
					`isLocked` int(11) NOT NULL DEFAULT '0',
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`)) ;"
				,
		"_contacts" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`firstName` varchar(100) NOT NULL DEFAULT ' ',
					`lastName` varchar(100) NOT NULL DEFAULT ' ',
					`emailAddress` varchar(100) NOT NULL DEFAULT ' ',
					`phoneNumber` varchar(100) NOT NULL DEFAULT ' ',
					`mobileNumber` varchar(100) NOT NULL DEFAULT ' ',
					`postAddress` varchar(100) NOT NULL DEFAULT ' ',
					`postAddress1` varchar(100) NOT NULL DEFAULT ' ',
					`city` varchar(100) NOT NULL DEFAULT ' ',
					`state` varchar(100) NOT NULL DEFAULT ' ',
					`zipcode` varchar(100) NOT NULL DEFAULT ' ',
					`hasGRAccount` int(11) NOT NULL DEFAULT '0',
					`grContact_id` varchar(100) NULL,
					`hasIsAccount` int(11) NOT NULL DEFAULT '0',
					`ISContact_id`  varchar(15) NULL,
					`ISContactGrps` longtext NULL,
					`ISMarketable` int(11) NOT NULL DEFAULT '0',
					`isOptIn` int(11) NOT NULL DEFAULT '1',
					`stripeCustId` varchar(100) NULL,
					`stripeEmail` varchar(100) NULL,
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',					
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`)) ;"
				,
		"_firsttimepricing" => "CREATE TABLE IF NOT EXISTS @table_name (
		 			`id` mediumint(9) NOT NULL AUTO_INCREMENT,
					`uniqueid` varchar(10) NOT NULL,
					`priceoption` numeric(10,2) NOT NULL DEFAULT '0',
					`prices` longtext NULL,
					`sortOrder` int(11) NOT NULL DEFAULT '0',
					`copyof` varchar(10) NOT NULL DEFAULT '0',					
					`isActive` int(11) NOT NULL DEFAULT '1',
					`isDelete` int(11) NOT NULL DEFAULT '0',
					`createdate` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
					 UNIQUE KEY `id` (`id`),KEY `uniqueid` (`uniqueid`)) ;"
				,
);

$methods_ajax = array(
		"_activateLicense" => array('func'=>'_activateLicense','user'=>false),
		"_deactivateLicense" => array('func'=>'_deactivateLicense','user'=>false),
		"_gethometypes" => array('func'=>'GetHomeType','user'=>false),
		"_savehometypes" => array('func'=>'SaveHomeTypee','user'=>false),
		"_copyhometypes" => array('func'=>'CopyHomeType','user'=>false),
		"_delhometypes" => array('func'=>'DelHomeTypepe','user'=>false),
		"_getfrequencies" => array('func'=>'GetFrequencies','user'=>false),
		"_savefrequencies" => array('func'=>'SaveFrequencies','user'=>false),
		"_copyfrequencies" => array('func'=>'CopyFrequencies','user'=>false),
		"_delfrequencies" => array('func'=>'DelFrequencies','user'=>false),
		"_savesyssettings" => array('func'=>'SaveSystemSettings','user'=>false),
		"_savestartprice" => array('func'=>'SaveStartPrice','user'=>false),
		"_getstartpricing" => array('func'=>'GetStartPricing','user'=>false),
		"_copystartpricing" => array('func'=>'CopyStartPricing','user'=>false),
		"_delstartpricing" => array('func'=>'DeleteStartPricing','user'=>false),
		"_getbedroompricing" => array('func'=>'GetBedroomPricing','user'=>false),
		"_savebedroomprice" => array('func'=>'SaveBedroomPrice','user'=>false),
		"_copybedroompricing" => array('func'=>'CopyBedroomPricing','user'=>false),
		"_delbedroompricing" => array('func'=>'DeleteBedroomPricing','user'=>false),
		"_getbathroompricing" => array('func'=>'GetBathroomPricing','user'=>false),
		"_savebathroomprice" => array('func'=>'SaveBathroomPrice','user'=>false),
		"_copybathroompricing" => array('func'=>'CopyBathroomPricing','user'=>false),
		"_delbathroompricing" => array('func'=>'DeleteBathroomPricing','user'=>false),
		"_getfrqpricing" => array('func'=>'GetFrqPricing','user'=>false),
		"_savefrqprice" => array('func'=>'SaveFrqPrice','user'=>false),
		"_copyfrqpricing" => array('func'=>'CopyFrqPricing','user'=>false),
		"_delfrqpricing" => array('func'=>'DeleteFrqPricing','user'=>false),
		"_getpetpricing" => array('func'=>'GetPetPricing','user'=>false),
		"_savepetprice" => array('func'=>'SavePetPrice','user'=>false),
		"_copypetpricing" => array('func'=>'CopyPetPricing','user'=>false),
		"_delpetpricing" => array('func'=>'DeletePetPricing','user'=>false),
		"_getStartPricingFrequency" => array('func'=>'GetStartPricingFrequency','user'=>true),
		"_getsqfpricing" => array('func'=>'GetSqFootagePricing','user'=>false),
		"_savesqfprice" => array('func'=>'SaveSqFootagePrice','user'=>false),
		"_copysqfpricing" => array('func'=>'CopySqFootagePricing','user'=>false),
		"_delsqfpricing" => array('func'=>'DeleteSqFootagePricing','user'=>false),
		"_getsqfpricingbyhnf" => array('func'=>'GetSqFPByHomeTypeNFrq','user'=>true),
		"_getsqfpricingbyf" => array('func'=>'GetSqFPByFrq','user'=>true),
		"_getservareapricing" => array('func'=>'GetServAreaPricing','user'=>false),
		"_saveservareaprice" => array('func'=>'SaveServAreaPrice','user'=>false),
		"_copyservareapricing" => array('func'=>'CopyServAreaPricing','user'=>false),
		"_delservareapricing" => array('func'=>'DeleteServAreaPricing','user'=>false),
		"_getavailabledates" => array('func'=>'GetAvailableDates','user'=>false),
		"_saveavailabledates" => array('func'=>'SaveAvailableDate','user'=>false),
		"_copyavailabledates" => array('func'=>'CopyAvailableDates','user'=>false),
		"_delavailabledates" => array('func'=>'DeleteAvailableDates','user'=>false),
		"_getsurchargerates" => array('func'=>'GetSurchargeRates','user'=>false),
		"_savesurchargerates" => array('func'=>'SaveSurchargeRate','user'=>false),
		"_copysurchargerates" => array('func'=>'CopySurchargeRates','user'=>false),
		"_delsurchargerates" => array('func'=>'DeleteSurchargeRates','user'=>false),
		"_getadditionalserv" => array('func'=>'GetAdditionalServs','user'=>false),
		"_saveadditionalserv" => array('func'=>'SaveAdditionalServ','user'=>false),
		"_copyadditionalserv" => array('func'=>'CopyAdditionalServs','user'=>false),
		"_deladditionalserv" => array('func'=>'DeleteAdditionalServs','user'=>false),
		"_getmarketingref" => array('func'=>'GetMarketingRefs','user'=>false),
		"_savemarketingref" => array('func'=>'SaveMarketingRef','user'=>false),
		"_copymarketingref" => array('func'=>'CopyMarketingRefs','user'=>false),
		"_delmarketingref" => array('func'=>'DeleteMarketingRefs','user'=>false),
		"_copyquote" => array('func'=>'CopyQuote','user'=>false),
		"_delquote" => array('func'=>'DeleteQuote','user'=>false),
		"_initQuote" => array('func'=>'_initQuote','user'=>true),
		"_getQuotes" => array('func'=>'GetQuotes','user'=>false),
		"_setQuoteValues" => array('func'=>'_setQuoteValues','user'=>true),
		"_setQuoteAddServValues" => array('func'=>'_setAddServiceChanges','user'=>true),
		"_getQuoteSummery" => array('func'=>'_getQuoteSummery','user'=>true),
		"_getQuoteSummeryFull" => array('func'=>'_getQuoteSummeryFull','user'=>true),
		"_saveQuoteContacts" => array('func'=>'_saveQuoteContacts','user'=>true),
		"_localizeScript" => array('func'=>'_localizeAjaxScript','user'=>true),
		"_customStyles" => array('func'=>'_customAjaxStyle','user'=>true),
		"_changeStatus" => array('func'=>'_changeStatus','user'=>true),
		"_savefirsttimeprices" => array('func'=>'SaveFirstTimePrices','user'=>false),
		"_getfirsttimeprices" => array('func'=>'GetFirstTimePrice','user'=>false),
		"_updatehourlyrate" => array('func'=>'_setHourlyrateValues','user'=>true),
		"_pmtsubmit" => array('func'=>'QuotePaymentSubmit','user'=>true),
		"_quoteexportdata" => array('func'=>'_QuoteExportData','user'=>false),
		"_createISContactByContact" => array('func'=>'_createISContactByContact','user'=>true),
		"_makeISContactMarketable" => array('func'=>'_makeISContactMarketable','user'=>true),
		"_iscallback" => array('func'=>'_infusionsoftcallback_','user'=>true),
);

$ShortCodeSettings = array(
	'MyMaidQuote' => '_getQuotePage'
);

$default_css_settings = array(
	"fontfamily" => "plugin-default",
	"fontsize" => "12px",
	"fontsizeadjust" => "none",
	"fontstretch" => "normal",
	"fontstyle" => "normal",
	"fontvariant" => "normal",
	"fontweight" => "normal",
	"lineheight" => "12px"
);

$sysMsg = array(
	0 => "Successfully Saved",
	1 => "Successfully Updated",
	2 => "Successfully Deleted",
	3 => "Successfully Copied"
);

$states = array (
		'AL'=>'Alabama',
		'AK'=>'Alaska',
		'AZ'=>'Arizona',
		'AR'=>'Arkansas',
		'CA'=>'California',
		'CO'=>'Colorado',
		'CT'=>'Connecticut',
		'DE'=>'Delaware',
		'DC'=>'District Of Columbia',
		'FL'=>'Florida',
		'GA'=>'Georgia',
		'HI'=>'Hawaii',
		'ID'=>'Idaho',
		'IL'=>'Illinois',
		'IN'=>'Indiana',
		'IA'=>'Iowa',
		'KS'=>'Kansas',
		'KY'=>'Kentucky',
		'LA'=>'Louisiana',
		'ME'=>'Maine',
		'MD'=>'Maryland',
		'MA'=>'Massachusetts',
		'MI'=>'Michigan',
		'MN'=>'Minnesota',
		'MS'=>'Mississippi',
		'MO'=>'Missouri',
		'MT'=>'Montana',
		'NE'=>'Nebraska',
		'NV'=>'Nevada',
		'NH'=>'New Hampshire',
		'NJ'=>'New Jersey',
		'NM'=>'New Mexico',
		'NY'=>'New York',
		'NC'=>'North Carolina',
		'ND'=>'North Dakota',
		'OH'=>'Ohio',
		'OK'=>'Oklahoma',
		'OR'=>'Oregon',
		'PA'=>'Pennsylvania',
		'RI'=>'Rhode Island',
		'SC'=>'South Carolina',
		'SD'=>'South Dakota',
		'TN'=>'Tennessee',
		'TX'=>'Texas',
		'UT'=>'Utah',
		'VT'=>'Vermont',
		'VA'=>'Virginia',
		'WA'=>'Washington',
		'WV'=>'West Virginia',
		'WI'=>'Wisconsin',
		'WY'=>'Wyoming',
);


